qa: fix: Fix static analysis continuous intergration step failed due to missing Wget dependency
The CI environments may not have GNU Wget installed.

This fixes the following error in the GitLab CI:

```output
Info: Downloading the prebuilt ShellCheck software archive...
./continuous-integration/do-static-analysis.install-system-deps.sh: line 248: wget: command not found
Error: Unable to download the prebuilt ShellCheck software archive...
```

Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>